
server:
  port: 8888

spring:
  datasource:
    name: testdb
    url: jdbc:mysql://192.168.1.158:3306/testdb?autoReconnect=true&useSSL=false
    username: bigtreemin
    password: xiaocao
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.test.bean